feat: add front
Palachyndra/SpaceBurgerShop pull request #5
Opened 2023-05-04 14:33 UTC by Palachyndra

2023-05-09 06:07 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Есть автологин
- Настроены редиректы
- Есть обработка ошибок запросов

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Не нужно делать запрос данных юзера если в хранилище нет токена

<img width="560" alt="Снимок экрана 2023-05-09 в 08 44 57" src="https://user-images.githubusercontent.com/60173362/237005002-53c6960e-3578-444b-8cea-fec3970949cf.png">

- Если юзер не авторизован, то у него не должен быть доступ к странице профиля

<img width="1431" alt="Снимок экрана 2023-05-09 в 08 48 06" src="https://user-images.githubusercontent.com/60173362/237005341-1da82365-1c5c-4da1-9772-6d026ce7d505.png">

- Если авторизоваться и обновить страницу, то на странице профиля пропадают данные юзера

- Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут `/login`. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью  `return <Navigate to={location?.state?.from || '/'} />;` (эти данные записываются в `ProtectedRoute`, а используются в `Login` для `Navigate)`

- По заданию в случае успешной отправки запроса восстановления пароля пользователь должен перенаправляться на маршрут` /reset-password`, сейчас этого не происходит, пользователь попадает на страницу логина
- Если сначала зайти под одним аккаунтом, а потом выйти и попытаться зарегистрировать новый, то авторизация происходит под предыдущим аккаунтом. Это хорошо видно на скриншоте. В форме данных профиля старый аккаунт, хотя в ответе на запрос регистрации совсем другие данные. Так же в этой ситуации невозможно разлогиниться, потому что запрос не передается токен.

<img width="1385" alt="Снимок экрана 2023-05-09 в 08 52 47" src="https://user-images.githubusercontent.com/60173362/237006156-9c93f189-9d5a-4e6d-b6e7-148ac4b78ba6.png">

- В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов".
- После запроса на изменение данных не нужно делать запрос на данные юзера - актуальные данные приходят в ответе на запрос на изменение. 
- Изменить пароль через форму данных на странице профиля невозможно, новый пароль не попадает в payload запроса.
- При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя. Для проверки ответа можете создать функцию, которая принимает `url` и опции запроса (хедеры и.т.п). Эта функция должна сначала сделать запрос по адресу с опциями, если запрос падает с ошибкой  `jwt-expired`, то нужно обновить accessToken с помощью refreshToken. После обновления необходимо просто повторить ранее неудавшийся запрос, но используя уже свежий токен.
- Если есть инпуты, то они должны быть внутри тега form, и на этот тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.
- Перенесите функции запросов в отдельный файл - `/utils/api.js`. Так же у вас есть несколько дубликатов функций - `setCookie` и `checkResponse`
- Для redux нужно подключить REDUX_DEVTOOLS

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-09 06:07 UTC, andryxxa93 commented on react-burger/src/components/app/app.jsx
> +            <Route path="/forgot-password" element={<ForgotPassword />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-05-09 06:07 UTC, andryxxa93 commented on react-burger/src/components/ingredient-details/ingredient-details.jsx
> +                "";
**Можно лучше**
Тут можно все массивы через spread оператор соединить в один и по нему искать -` [...bun, ...main, ....souce].filter((item) => ...)`

2023-05-09 06:07 UTC, andryxxa93 commented on react-burger/src/pages/forgot-password.jsx
> +  const checkResponse = (res) => {
**Можно лучше**

проверка ответа сервера и преобразование из json дублируется в нескольких местах, нужно вынести в отдельную функцию:

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2023-05-09 06:07 UTC, andryxxa93 commented on react-burger/src/pages/login.jsx
> +    const Authorization = () => {
**Можно лучше**
Запрос лучше держать в отдельном файле

2023-05-13 15:30 UTC, Palachyndra commented on react-burger/src/components/app/app.jsx
> +            <Route path="/forgot-password" element={<ForgotPassword />} />
Отпишусь здесь перед след PR, тк больше некуда :
- я не знаю, почему не работает  REDUX_DEVTOOLS. Перестал работать после подключения. Ни один из способов решить проблему - не помог.
- переговорил с наставником по поводу onSubmit - "это правда. но форма считается более семантически правильным и доступным решением". Поэтому не считаю, что onClick является критическим замечанием и что его требуется исправить. Логика условно будет той же самой, просто более правильной что ли.

2023-05-14 08:15 UTC, andryxxa93 commented
**Необходимо исправить**
- Если авторизоваться и обновить страницу, то происходит запрос данных юзера, а потом обновление токена - последнее лишнее. Обновление токена нужно только в случае протухания acessToken.
- В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов".
- При запросах, использующих accessToken, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя. Для проверки ответа можете создать функцию, которая принимает url и опции запроса (хедеры и.т.п). Эта функция должна сначала сделать запрос по адресу с опциями, если запрос падает с ошибкой jwt-expired, то нужно обновить accessToken с помощью refreshToken. После обновления необходимо просто повторить ранее неудавшийся запрос, но используя уже свежий токен.

<img width="1317" alt="Снимок экрана 2023-05-14 в 11 15 19" src="https://github.com/Palachyndra/SpaceBurgerShop/assets/60173362/a0411126-303e-45a2-9c7e-86de5f3ad1f2">

2023-05-15 06:39 UTC, andryxxa93 commented
**Необходимо исправить**
Обновление токена так же должно работать при изменении данных юзера. 

Для этого используйте обертку над fetch, примерно такую
```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options); //делаем запрос
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken(); //обновляем токен
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      localStorage.setItem("accessToken", refreshData.accessToken); //(или в cookies)
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options); //вызываем перезапрос данных
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```


Поправьте этот момент и работа будет принята!

2023-05-15 17:33 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-24 12:36 UTC, merged