refactor: from js to ts
Palachyndra/SpaceBurgerShop pull request #6
Opened 2023-05-27 12:04 UTC by Palachyndra

2023-05-27 12:44 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Типизировали все необходимые файлы
- Использовали `as` в правильных ситуациях 

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- В проекте много `any` от которых можно избавиться. Это не касается тех, что связаны со хранилищем и `redux`. 
- Функция `checkResponse ` дублируется несколько раз - необходимо удалить дубликаты и использовать одну версию

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-27 12:44 UTC, andryxxa93 commented on react-burger/src/components/modal/modal.tsx
> +const Modal = (props: any) => {
**Необходимо исправить**
Вот здесь и других подобных местах нужно избавиться от `any`

2023-05-27 12:44 UTC, andryxxa93 commented on react-burger/src/components/order-details/order-details.tsx
> +// OrderDetails.propTypes =
**Можно улучшить**
Ненужный код лучше удалять

2023-05-27 12:44 UTC, andryxxa93 commented on react-burger/src/pages/forgot-password.tsx
> +  const checkResponse = (res: any) => {
**Необходимо исправить**
Тут можно использовать тип `Response`

2023-05-27 12:44 UTC, andryxxa93 commented on react-burger/src/components/burger-constructor/burger-constructor.tsx
> +                                    // @ts-ignore - если так нельзя, то подскажите пж, как это можно исправить
**Можно лучше**
От этого ts-ignore вы сможите полностью избавиться когда типизируете хранилище. 
Но чтобы не ругалось на `TopBun ` возвращаете из него null если тип не `if (props.types === "top")`

2023-05-27 12:44 UTC, andryxxa93 commented on react-burger/src/components/burger-constructor/burger-constructor.tsx
> +                            // @ts-ignore - подскажите пж, как это можно исправить
Тут вы сможете избавиться от `ts-ignore` когда типизируете хранилище

2023-05-28 07:48 UTC, Palachyndra commented on react-burger/src/components/burger-constructor/burger-constructor.tsx
> +                                    // @ts-ignore - если так нельзя, то подскажите пж, как это можно исправить
Спасибо, тогда пока что так оставлю

2023-05-28 19:04 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-06-03 04:10 UTC, merged