feat: add tests on jest
Palachyndra/SpaceBurgerShop pull request #8
Opened 2023-06-25 02:48 UTC by Palachyndra

2023-06-25 09:09 UTC, ArslanMustafin commented
> Залил на github.io, но что-то страница показывает до сих пор README, хотя говорилось, что до 20 мин. Может быть проблема в том, что у меня еще одна папка react-burger, может еще не создалось.

Здравствуйте, у вас нету ветки `gh-pages` поэтому скорее всего и не хочет раскатываться `react` приложение. Советую обратиться за помощью к наставнику) или найти гайд какой-нить, по установке `CRA` приложения на `gh-pages`.

2023-06-25 09:09 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Все юнит-тесты (17 шт) проходят успешно
- Все Cypress тесты проходят успешно
- В readme есть ссылка на проект.

### **Есть несколько замечаний, которые нужно исправить:**

- Добавьте команду в `package.json` для открытия cypres: `"cypress:open": "./node_modules/.bin/cypress open"`, так намного удобнее запускать cypress.;

- Лучше вынести базовый адрес сервера в конфиг cypress.
  <https://docs.cypress.io/guides/references/best-practices#Cypress-configuration-file>

- Токены доступа лучше вынести в константы, также, для этого можно использовать env от Cypress: <https://docs.cypress.io/api/cypress-api/env>

### **Сделает код лучше:**

- Чтобы проверить процент покрытия тестами всех файлов, используйте команду `react-scripts test --coverage --watchAll`

- Лучше мокать запросы к серверу в `cypress` тестах (да и в обычных тоже);

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>;

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2023-06-25 09:09 UTC, ArslanMustafin commented on react-burger/cypress/e2e/burger-constructor.cy.js
> +  const password = "admin123";
**Надо исправить:**

токены доступа лучше вынести в константы, также, для этого можно использовать env от Cypress: <https://docs.cypress.io/api/cypress-api/env>

2023-06-25 09:09 UTC, ArslanMustafin commented on react-burger/cypress/e2e/burger-constructor.cy.js
> +  const localUrl = "http://localhost:3000";
**Надо исправить:**

лучше вынести базовый адрес сервера в конфиг cypress.

<https://docs.cypress.io/guides/references/best-practices#Cypress-configuration-file>

2023-06-25 09:09 UTC, ArslanMustafin commented on react-burger/cypress/e2e/burger-constructor.cy.js
> +    cy.get('[data-testid=main]').contains('Плоды Фалленианского дерева').trigger('dragstart');
**Можно лучше%:**

повторяющиеся данные, да и вообще данные для тестирования лучше вынести в константы.

```js
const testBun = "Краторная булка N-200i";
const testIngredient = "Плоды Фалленианского дерева";

cy.get('[data-testid=bun]').contains(testBun).trigger('dragstart');
cy.get('[data-testid=constructor-ingredients]').contains(testIngredient).trigger('dragstart');
```

2023-06-25 09:09 UTC, ArslanMustafin commented on react-burger/cypress/e2e/modal.cy.js
> +  const localUrl = "http://localhost:3000";
**Надо исправить:**

лучше вынести базовый адрес сервера в конфиг cypress.

<https://docs.cypress.io/guides/references/best-practices#Cypress-configuration-file>

2023-06-25 10:17 UTC, Palachyndra commented
> > Залил на github.io, но что-то страница показывает до сих пор README, хотя говорилось, что до 20 мин. Может быть проблема в том, что у меня еще одна папка react-burger, может еще не создалось.
> 
> Здравствуйте, у вас нету ветки `gh-pages` поэтому скорее всего и не хочет раскатываться `react` приложение. Советую обратиться за помощью к наставнику) или найти гайд какой-нить, по установке `CRA` приложения на `gh-pages`.

@ArslanMustafin Сделал, спасибо. Но тк немного криво сделал изначально, из-за подпапки, то изначально стрн пустая. Потом MR смержу и вынесу все это из подпапки, чтобы сейчас не было куча правок.

2023-06-26 05:51 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.🔥

### **Вы молодец! Работа принята.**

- Все замечания были исправлены.

Несколько советов для дальнейшего развития:

- Сверстайте несколько небольших проектов для себя, для закрепления знаний, и чтобы можно добавить их в портфолио.

- Ходите на собеседования: опыт прохождения собеседований не менее важен знаний теории, и Вы поймете, какие знания требуются на рынке, и где Вы проседаете.

- Читайте habr и слушаете подкаксты: они очень хорошо расширяют кругозор и позволяют узнать, что происходит в отрасли.

### **Сделает код лучше:**

- Ссылка есть, но поработайте ещё над роутингом (Почитайте, какие есть подводные камни в использовании `react router` и `gh-pages`), ну и чтобы сразу главная страница отображалась, а не пустота;

2024-05-29 09:53 UTC, merged